markdown: kramdown
highlighter: rouge
baseurl: ""
permalink: /blog/:year/:month/:day/:title/
exclude:
  - CNAME
  - '*.sublime-project'
  - '*.sublime-workspace'
  - package.json
  - node_modules/
  - 'webpack.*.js'
  - yarn.lock
  - src/
